# Generated by Django 2.2.7 on 2019-11-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.TextField(default='{"eng": "", "rus": ""}', verbose_name='Car name'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Сar busy?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
