# Generated by Django 2.2.7 on 2019-12-04 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rent_app', '0003_auto_20191130_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='add_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.TextField(default='{"eng": "", "rus": ""}', verbose_name='Название автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Машина занята?'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_of_issue',
            field=models.DateField(verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
